### PR TITLE
Add benchmarks

### PR DESCRIPTION
**Pull request by GretaCB**
Per https://github.com/mapbox/hpp-skel/issues/33, add bench tests so we can measure performance going forward, specifically API changes in https://github.com/mapbox/gzip-hpp/pull/5

### Next Actions
- [x] Troubleshoot compile errors
- [x] Add benchmarks for both decompress and compress

There have been a few improvements in hpp-skel since I ported this over. Planning to add those in a separate PR (format, tidy, Debug config, etc)

cc @springmeyer

### CODE REVIEW

**Comment by springmeyer** [comment]
The `bench-tests` will also need to link the dependent libraries like:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a033e16..1da673c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -28,4 +28,5 @@ file(GLOB BENCH_SOURCES bench/*.cpp)
 add_executable(bench-tests ${BENCH_SOURCES})
 
 # link zlib static library to the unit-tests binary so the tests know where to find the zlib impl code
+target_link_libraries(bench-tests ${MASON_PACKAGE_benchmark_STATIC_LIBS} ${CMAKE_THREAD_LIBS_INIT} ${MASON_PACKAGE_zlib_STATIC_LIBS})
 target_link_libraries(unit-tests ${MASON_PACKAGE_zlib_STATIC_LIBS})
```

**Comment by GretaCB** [comment]
Thanks for the tip @springmeyer 👍 , did the trick. 

Update:
- Benchmark went smooth when compressing a string. Next step I'm working on is benchmarking an mvt file. This will require some setup code, which I'm currently troubleshooting. Atm, benchmarking is stalling locally and hitting `/bin/sh: line 1: 10473 Killed: 9               ./build/bench-tests`. So I plan to profile and see what is churning.

**Comment by springmeyer** [comment]
> Atm, benchmarking is stalling locally and hitting /bin/sh: line 1: 10473 Killed: 9 ./build/bench-tests.

perhaps because you are opening the file per benchmark iteration, which could be very expensive. (profiling would show this). If I'm right, then I recommend opening the file inside the `main()` and then passing the data to the benchmark as an argument (that can be pulled out of the state).

**Comment by GretaCB** [comment]
Not completely sure why the single Travis `g++-5` test is failing. @danpat suggested it could be due to some c++14 feature not supported in c++11, but technically google benchmark [should be fine](https://github.com/google/benchmark#compiler-support). Also, setting `CMAKE_CXX_STANDARD` from 11 to 14 didnt help either.

Going to set this down for a bit and chomp on the werror PR

**Comment by springmeyer** [comment]
Took at look at this yesterday with @GretaCB and found that converting the functions to C++11 lambdas is what the `BENCHMARK` macros is doing internally. We don't use that macro, so that we can pass additional, arbitrary non-numeric arguments. So we can get this working for both clang++ and g++ by doing https://github.com/mapbox/gzip-hpp/compare/bench...lambdah. @GretaCB, want to revert the `c++14` attempt to fix, and then apply the lambda approach and merge after?

**Pull request merged**
