### PR TITLE
[TESTING] Boost comparison bench

### PR DESCRIPTION
**Pull request by GretaCB**
Continuation of https://github.com/mapbox/gzip-hpp/pull/7

### CODE REVIEW

**Comment by GretaCB** [comment]
Findings from failed tests:
- Not sending proper compress_data.size() in many(?) tests (line 54 in `test.cpp`)
- Segfault triggered from [`fail compress- throws max size limit`](https://github.com/mapbox/gzip-hpp/blob/master/test/test.cpp#L23) test. Report the bug upstream to boost, linking to Dane's [gist of the crash log](https://gist.github.com/springmeyer/9e474a299b1733ee3350d423aebcee67).

**Comment by GretaCB** [comment]
Revised bench results with the filestream fix

### gzip-hpp

screenshot 2017-10-04 15 49 07

### boost

screenshot 2017-10-04 15 53 37

**Comment by GretaCB** [comment]
Hey @springmeyer , trying to remember where we left off with the Segfault [here](https://github.com/mapbox/gzip-hpp/pull/16#issuecomment-334177428). Was it due to the filestream issue you discovered? No longer need to create Boost ticket?

**Comment by springmeyer** [comment]
>  Hey @springmeyer , trying to remember where we left off with the Segfault here. Was it due to the filestream issue you discovered? No longer need to create Boost ticket?

We discovered it is not a problem for us / requires no action in gzip-hpp. So good have this ticket closed. However it looks like a bug in boost::iostreams library that our tests uncovered. So the next action would be to create a reduced testcase that triggers the bug and then share that in a boost bug report. A reduced testcase would be a `test.cpp` that replicates the crash without using our wrapper and only the boost API. @GretaCB we could pair on this together? Maybe next week?

**Pull request closed without merging**
