### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by GretaCB**
Add gzip-specific docs to readme.

### Next Actions
- [x] Enable Travis tests and Uudate Travis badge link
- [x] Get tests passing 🍏, fix [current AddressSanitizer failure](https://travis-ci.com/mapbox/gzip-hpp/jobs/88334656#L440)
- [x] Add pointer compress/decompress tests. Right now there are only `std::string` tests.
- [x] Update versioning test/code (currently commented out)
- [x] Update versioning section in Readme after ^^^ is finished
- [x] Code Review

cc @mapsam @springmeyer

### CODE REVIEW

**Comment by mapsam** [comment]
Thanks @GretaCB! Quick question - the README includes examples about how to compress/uncompress `std::string` - any idea if this can be used on other data types, such as a `node::Buffer::Data`?

**Comment by GretaCB** [comment]
@mapsam great question. Perhaps try something like:
```
    char * buf_data = node::Buffer::Data(data);
    std::string value = gzip::compress(buf_data);
```

**Comment by GretaCB** [comment]
@springmeyer should gzip-hpp be verifying that size is passed in when accessed directly from the pointer method?

**Comment by springmeyer** [comment]
> @springmeyer should gzip-hpp be verifying that size is passed in when accessed directly from the pointer method?

Per chat the problem we found is that:

```c++
    std::string data = "hello";
    std::string value = gzip::compress(data);
```

Dispatches, correctly, to the `compress` function taking a `std::string const&` at https://github.com/mapbox/gzip-hpp/blob/d3a8a0804691de9df885b1bcdad160b01b42c865/include/gzip/compress.hpp#L54

But

```c++
    std::string value = gzip::compress("hello");
```

or

```c++
    std::string data = "hello";
    const char * pointer = data.data();
    std::string value = gzip::compress("hello");
```

Both compile, when ideally they should not. They are ending up also dispatching to the `compress` function taking a `std::string const&` at https://github.com/mapbox/gzip-hpp/blob/d3a8a0804691de9df885b1bcdad160b01b42c865/include/gzip/compress.hpp#L54 

This is not good because:

 - Implicit conversion is happening, leading to a copy of the data being creating in a new `std::string` that does not have clear ownership.
 - It is totally not obvious to the user they are misusing the function

So, tentative proposals we will consider in a followup PR are:

Option 1. Consider deleting the function that matches `compress(const * char)` to trigger a compile error to prevent misuage and a copy:

```
template <class T>
std::string compress(T) = delete;
```
Per https://stackoverflow.com/a/12877589

Option 2. Remove the signature that accepts a `std::string` to avoid it being potentially used without being intended to be used.

**Pull request merged**
